// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wugcvaheypvrcotsmbgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1Z2N2YWhleXB2cmNvdHNtYmdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjIyNTcsImV4cCI6MjA2OTQ5ODI1N30.BzbwzixcnaROR8VRbDQuOFfqj25SFXw6jSMGupaC6CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});